# Generated by Django 6.0.5 on 2026-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlogin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
