# Generated by Django 6.0.5 on 2026-06-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
