# Generated by Django 6.0.5 on 2026-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0005_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.AddField(
            model_name='car',
            name='driver_ph_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
