# Generated by Django 6.0.5 on 2026-06-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0006_remove_car_created_at_car_driver_ph_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver_ph_no',
        ),
    ]
