# Generated by Django 6.0.5 on 2026-06-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0007_remove_car_driver_ph_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
