# Generated by Django 6.0.5 on 2026-06-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0011_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
