# Generated by Django 6.0.5 on 2026-06-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0014_delete_newcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('rent_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('ac', models.BooleanField(default=True)),
                ('power_steering', models.BooleanField(default=True)),
                ('power_windows', models.BooleanField(default=True)),
                ('music_system', models.BooleanField(default=False)),
                ('airbags', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='myaddminpanel.vendorlogin')),
            ],
        ),
    ]
