# Generated by Django 6.0.5 on 2026-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0015_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=225)),
                ('driver_license_number', models.CharField(max_length=50)),
                ('driver_license_expiry', models.DateField()),
                ('driver_age', models.PositiveIntegerField()),
                ('driver_ph_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
