# Generated by Django 6.0.5 on 2026-06-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0017_car_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
