# Generated by Django 6.0.5 on 2026-06-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddminpanel', '0018_remove_car_driver_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=225)),
                ('driver_license_number', models.CharField(max_length=50)),
                ('driver_license_expiry', models.DateField()),
                ('driver_age', models.PositiveIntegerField()),
                ('driver_ph_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='myaddminpanel.vendorlogin')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myaddminpanel.driver'),
        ),
    ]
